import type { NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import { customAlphabet } from "nanoid"
import { trpc } from "../utils/trpc"

const nanoid = customAlphabet("abcdefghijklmnopqrstuvwxyz123456789", 10)

const Home: NextPage = () => {
  const router = useRouter()

  function createRoom() {
    const roomId = nanoid()

    router.push(`/room/${roomId}`)
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center w-1/2 min-h-screen mx-auto">
        <button onClick={createRoom}>CREATE ROOM</button>
      </div>
    </>
  )
}

export default Home
