import type { NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import { customAlphabet } from "nanoid"
import { trpc } from "../utils/trpc"
import { useSession, signIn, signOut } from "next-auth/react"

const nanoid = customAlphabet("abcdefghijklmnopqrstuvwxyz123456789", 10)

const Home: NextPage = () => {
  const { data: session } = useSession()
  const router = useRouter()

  function createRoom() {
    const roomId = nanoid()

    router.push(`/room/${roomId}`)
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session && (
        <div className="flex flex-col items-center justify-center w-1/2 min-h-screen mx-auto">
          <p>Hey {session.user?.name}! Do you want to create a chat room?</p>
          <button onClick={createRoom}>CREATE ROOM</button>
        </div>
      )}

      {!session && <button onClick={() => signIn()}>Sign in</button>}
    </>
  )
}

export default Home
